py_web/models.py
from .database import db
from py_web.ext import bcrypt


class User(db.Model):
    # __tablename__ = 't_user'
    id = db.Column(db.Integer(), primary_key=True)
    username = db.Column(db.String(255))
    password = db.Column(db.String(255))
    posts = db.relationship('Post', backref='user', lazy='dynamic')

    def __init__(self, username, password):
        self.username = username
        self.set_password(password)

    def __str__(self, username):
        self.username = username

    def set_password(self, password):
        self.password = bcrypt.generate_password_hash(password)

    def check_password(self, password):
        return bcrypt.check_password_hash(self.password, password)

    def __repr__(self):
        return '<User %r>' % (self.name)

tags = db.Table('post_tags',
                db.Column('post_id', db.Integer, db.ForeignKey('post.id'), primary_key=True),
                db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'), primary_key=True))


class Post(db.Model):
    # __tablename__ = 't_post'
    id = db.Column(db.Integer(), primary_key=True)
    title = db.Column(db.String(255), nullable=False)
    text = db.Column(db.Text())
    pub_date = db.Column(db.DateTime())
    user_id = db.Column(db.Integer(), db.ForeignKey('user.id'))
    comments = db.relationship('Comment', backref='post', lazy='dynamic')
    tags = db.relationship('Tag', secondary=tags, backref=db.backref('posts', lazy='dynamic'))

    def __init__(self, title):
        self.title = title

    def __str__(self):
        return "<Post '{}'>".format(self.title)


class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(255))

    def __init__(self, title):
        self.title = title

    def __str__(self):
        return "<Tag '{}'>".format(self.title)


class Comment(db.Model):
    # __tablename__ = 't_comment'
    id = db.Column(db.Integer, primary_key=True)
    text = db.Column(db.Text())
    date = db.Column(db.DateTime())
    post_id = db.Column(db.Integer, db.ForeignKey('post.id'))

    def __str__(self):
        return "<Comment '{}'>".format(self.text[:5])

class UploadFile(db.Model):


    def __init__(self,filename):
        self.filename=filename


    id=db.Column(db.Integer(),primary_key=True)
    filename=db.Column(db.String(255))
    upload_date=db.Column(db.DateTime())

py_web/forms.py
from flask_wtf import FlaskForm
from wtforms import BooleanField, StringField, PasswordField, validators,FileField,TextAreaField





class RegistrationForm(FlaskForm):
    username = StringField('Username', [validators.Length(min=2, max=25)])
    # email = StringField('Email Address', [validators.Length(min=6, max=35)])
    password = PasswordField('New Password', [
        validators.DataRequired(),
        validators.EqualTo('confirm', message='Passwords must match')
    ])
    confirm = PasswordField('Repeat Password')
    accept_tos = BooleanField('I accept the TOS', [validators.DataRequired()])

class LoginForm(FlaskForm):
    username = StringField('Username', [validators.Length(min=2, max=25),validators.DataRequired()])
    password = PasswordField('Password', [validators.DataRequired()])

class UploadForm(FlaskForm):
    file=FileField('File Name',[validators.DataRequired()])



class CommentForm(FlaskForm):
    text=TextAreaField('Comment',[validators.DataRequired()])

py_web/__init__.py
from flask import Flask

from .database import db
from py_web.controllers.auth import auth
from py_web.controllers.upload import upload
from py_web.controllers.blog import blog
from py_web.ext import bcrypt
# from flask_uploads import configure_uploads
from flask import redirect,url_for

def create_app(Config_obj):
    app = Flask(__name__)

    app.config.from_object(Config_obj)

    db.init_app(app)
    bcrypt.init_app(app)
    # configure_uploads(app, (file,))

    @app.route('/')
    def index():
        return redirect(url_for('blog.blog_home'))
    app.register_blueprint(blog)
    app.register_blueprint(auth)
    app.register_blueprint(upload)



    return app

py_web/controllers/auth.py
from flask import (Blueprint, flash, redirect, render_template, request, session, url_for, g)
from functools import wraps
from py_web.database import db
from py_web.models import User
from py_web.forms import RegistrationForm,LoginForm

auth = Blueprint('auth', __name__, url_prefix='/auth')


def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if g.user is None:
            return redirect(url_for('login', next=request.url))
        return f(*args, **kwargs)

    return decorated_function


@auth.route('/register', methods=('GET', 'POST'))
def register():
    form=RegistrationForm()
    if form.validate_on_submit():
        if User.query.filter_by(username=form.username.data).first():
            flash('User {} is already registered.'.format(form.username.data),category='danger')
        user=User(username=form.username.data,password=form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Thanks for registering!Please login.',category='Success')
        return redirect(url_for('auth/login'))
    return render_template('auth/register.html', form=form)


@auth.route('/login', methods=('GET', 'POST'))
def login():
    form=LoginForm()
    if form.validate_on_submit():
        user=User.query.filter_by(username=form.username.data).first()
        error=None
        if user is None:
            error='Incorrect username.'
        elif not user.check_password(form.password.data):
            error='Incorrect password.'
        if error is None:
            session.clear()
            session['user_id']=user.id
            # flash('Login success!',category='success')
            return redirect(url_for('auth.index'))
        flash(error, category='danger')

    return render_template('auth/login.html', form=form)



@auth.route('/',methods=['GET','POST'])
def index():
    form=LoginForm()
    if request.method=='POST' and form.validate():
        if form.username.data:
            flash('dsafasdsdf',category='info')
            # redirect(url_for('auth.index'))
    # flash('dsdsds',category='info')
    return render_template('upload/test_form.html',form=form)

py_web/controllers/blog.py
from sqlalchemy import func
from py_web.models import Post, Tag, Comment, tags
from py_web.database import db
from flask import (redirect, render_template, flash, url_for, Blueprint)
from py_web.forms import CommentForm
from datetime import datetime

def siderbar_data():
    recent = Post.query.order_by(Post.pub_date.desc()).limit(5).all()

    top_tags = db.session.query(Tag, func.count(tags.c.post_id).label('total')).join(
        tags
    ).group_by(Tag).order_by('total DESC').limit(5).all()
    return recent, top_tags


blog = Blueprint('blog',__name__, url_prefix='/blog')


@blog.route('/')
@blog.route('/<int:page>')
def blog_home(page=1):
    posts = Post.query.order_by(Post.pub_date.desc()).paginate(page, 10)
    recent, top_tags = siderbar_data()

    return render_template('blog/blog_home.html',
                           posts=posts,
                           recent=recent,
                           top_tags=top_tags)



@blog.route('/post/<int:post_id>',methods=['GET','POST'])
def post(post_id):
    form=CommentForm()
    if form.validate_on_submit():
        new_comment=Comment(text=form.text.data,date=datetime.now(),post_id=post_id)
        db.session.add(new_comment)
        db.session.commit()
    post=Post.query.get_or_404(post_id)
    tags=post.tags
    comments=post.comments.order_by(Comment.date.desc()).all()
    recent,top_tags=siderbar_data()


    return render_template('blog/post.html',
                           post=post,
                           tags=tags,
                           comments=comments,
                           recent=recent,
                           top_tags=top_tags,
                           form=form
                           )

py_web/controllers/upload.py
import os
from flask import (flash, request, redirect, url_for, Blueprint, current_app,render_template,
                   send_from_directory
                   )
from werkzeug.utils import secure_filename
from py_web.models import UploadFile
from datetime import datetime
from py_web.database import db
from py_web.ext import file
from py_web.forms import UploadForm,LoginForm




upload = Blueprint('upload', __name__, url_prefix='/upload')

ALLOWED_EXTENSIONS = {'txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif','csv'}

def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


@upload.route('/', methods=['GET', 'POST'])
def upload_file():
    if request.method == 'POST':
        # check if the post request has the file part
        if 'file' not in request.files:
            flash('No file part')
            return redirect(request.url)
        file = request.files['file']
        # if user does not select file, browser also
        # submit an empty part without filename
        if file.filename == '':
            flash('No selected file')
            return redirect(request.url)
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)

            file.save(os.path.join(current_app.config['UPLOAD_FOLDER'], filename))
            new_file=UploadFile(filename)
            new_file.upload_date=datetime.now()
            db.session.add(new_file)
            db.session.commit()
            return redirect(url_for('upload.file_list'))
    return render_template('upload/upload.html')
# def upload_file():
#     form=UploadForm()
#     # if form.validate_on_submit():
#     if request.method=='POST':
#         file=request
#         filename = file.save(request.files['files'])
#         if filename:
#             filename = secure_filename(file.filename)
#             new_file=UploadFile(filename)
#             new_file.upload_date=datetime.now()
#             db.session.add(new_file)
#             db.session.commit()
#             flash('file uploaded',category='success')
#             return redirect(url_for('upload.file_list'))
#     return render_template('upload/upload.html',form=form)

@upload.route('/file_list',methods=['GET'])
def file_list():
    files=UploadFile.query.all()
    return render_template('upload/file_list.html',file=files)


@upload.route('/download/<int:id>')
def uploaded_file(id):
    file=UploadFile.query.get(id)
    return send_from_directory(current_app.config['UPLOAD_FOLDER'],
                                   file.filename)


@upload.route('/1')
def test_forms():
    form=LoginForm()
    if form.validate_on_submit():
        pass
    return render_template('upload/test_form.html',form=form)

py_web/templates/blog/blog_home.html
{% extends 'base.html' %}
{% block header %}
Blog
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-9">
        {% for post in posts.items %}
            <div class="row">
                <div class="col-md-12">
                    <h1>{{ post.title }}</h1>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    {{ post.text|truncate(255)|safe }}
                    <a href="{{ url_for('blog.post',post_id=post.id) }}"><small>Read More</small></a>
                </div>
            </div>
        {% endfor %}
        
    </div>
    <div class="col-md-3">
        <div class="row">
            <h5>Recent Blogs</h5>
            <ul>
                {% for post in recent %}
                    <li><a href="{{ url_for('blog.post',post_id=post.id) }}">{{ post.title }}</a></li>
                {% endfor %}
                
            </ul>
        </div>
        <div class="row">
            <h5>Popular Tags</h5>
            <ul>
                {% for tag in top_tags %}
                    <li><a href="{{ url_for('blog.tag',tag_name=tag[0].title) }}">{{ tag[0].title }}</a></li>
                {% endfor %}
                
            </ul>
        </div>
    </div>
</div>
{% endblock %}

py_web/templates/blog/post.html
{% extends 'base.html' %}
{% from '_formhelper.html' import render_field %}
{% block title %}
    Post-{{ post.title }}
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-9">
            <div class="page-header">{{ post.title }}</div>
            {{ post.text }}
            <hr>
            <form action="{{ url_for('blog.post', post_id=post.id) }}" method="post">
                {{ form.hidden_tag() }}
                {{ render_field(form.text) }}
                <button type="submit" class="btn btn-primary">Add Comment</button>
            </form>
            <hr>
            {% if comments %}
                <ul>
                    {% for comment in comments %}
                        <li>{{ comment }}</li>
                    {% endfor %}

                </ul>

            {% endif %}
        </div>

        <div class="col-md-3">
            <div class="row">
                <h5>Recent Blogs</h5>
                <ul>
                    {% for post in recent %}
                        <li><a href="{{ url_for('blog.post',post_id=post.id) }}">{{ post.title }}</a></li>
                    {% endfor %}

                </ul>
            </div>
            <div class="row">
                <h5>Popular Tags</h5>
                <ul>
                    {% for tag in top_tags %}
                        <li><a href="{{ url_for('blog.tag',tag_name=tag[0].title) }}">{{ tag[0].title }}</a></li>
                    {% endfor %}

                </ul>
            </div>
        </div>
    </div>
{% endblock %}